In [47]:
import scipy.io
import scipy.misc
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
import numpy as np
# import tensorflow as tf
import tensorflow.compat.v1 as tf   # this line is using so that can use precious version function so we need not to shift to previous versoin
tf.disable_v2_behavior()
# https://www.analyticsvidhya.com/blog/2020/10/introduction-and-implementation-to-neural-style-transfer-deep-learning/
%matplotlib inline


In [48]:
path="pretrained-model/imagenet-vgg-verydeep-19.mat"
vgg = scipy.io.loadmat(path)

In [49]:
print(type(vgg))

<class 'dict'>


In [50]:
print(vgg.keys())

dict_keys(['__header__', '__version__', '__globals__', 'layers', 'meta'])


In [51]:
print(vgg['__header__'])

b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Fri Sep 30 08:35:35 2016'


In [52]:
# print(vgg['layers'])

In [53]:
# only have to deal with vgg['layers']
vgg_l=vgg['layers']

In [54]:
print(type(vgg_l))
print(vgg_l.shape)

<class 'numpy.ndarray'>
(1, 43)


In [70]:
# https://programmersought.com/article/11411093826/
# print(vgg_l[0][0][0][0][0])   #layer_name       
# print(vgg_l[0][0][0][0][1])    # layer_type
# print(vgg_l[0][0][0][0][2])  # w, b
# print(vgg_l[0][0][0][0][2][0][0].shape) # w  (3,3,3,64) (height,width,3d image, no. of filters)
# print(vgg_l[0][0][0][0][3][0][1])  #  b single value
print(vgg_l[0][0][0][0][4])    # might pad     
print(vgg_l[0][0][0][0][5])     # might stride
print(vgg_l[0][0][0][0][6])      
print(vgg_l[0][0][0][0][7])
print(vgg_l[0][0][0][0][8])      # empty
# print(vgg_l[0][0][0][0][9])   out of index


[[1 1 1 1]]
[[1 1]]
[[0]]
[[1]]
[]


In [71]:
print(vgg_l[0][1][0][0][0])   #layer _name      (fixed, layer(0-42),zero,zero,(layer_name,layer,(w,b),))
print(vgg_l[0][1][0][0][1])   #layer type
print(vgg_l[0][1][0][0][2])  # w, b
# print(vgg_l[0][1][0][0][2][0][0].shape) # w  (3,3,3,64) (height,width,3d image, no. of filters)
# print(vgg_l[0][1][0][0][3][0][1])  #  b single value
print(vgg_l[0][1][0][0][4])         
# print(vgg_l[0][1][0][0][5])   out of bound since relu
# print(vgg_l[0][1][0][0][6])
# print(vgg_l[0][1][0][0][7])
# print(vgg_l[0][1][0][0][8])
# print(vgg_l[0][1][0][0][9])   

['relu1_1']
['relu']
[[0]]
[[0]]


In [75]:
# https://programmersought.com/article/11411093826/
print(vgg_l[0][2][0][0][0])   #layer_name    (con1_2)    
print(vgg_l[0][2][0][0][1])    # layer_type  (conv)
# print(vgg_l[0][2][0][0][2])  # w, b
print(vgg_l[0][2][0][0][2][0][0].shape) # w  (3,3,64,64) (height,width,3d image, no. of filters) because before this im size=x,y,64
print(vgg_l[0][2][0][0][3][0][1])  #  b single value
print(vgg_l[0][2][0][0][4])         
print(vgg_l[0][2][0][0][5])
print(vgg_l[0][2][0][0][6])
print(vgg_l[0][2][0][0][7])
print(vgg_l[0][2][0][0][8])
# print(vgg_l[0][0][0][0][9])   out of index

['conv1_2']
['conv']
(3, 3, 64, 64)
3
[[1 1 1 1]]
[[1 1]]
[[0]]
[[1]]
[]
